### PR TITLE
Eclipse code style and .gitattributes #167

### PR DESCRIPTION
**Pull request by pauldaustin**
Updated the eclipse formatting profile.

Added an eclipse code cleanup profile.

Added a screen shot of the eclipse save actions on a project.

Normalized line endings on files.

Ran the code cleanup and formatting on all the java source

### CODE REVIEW

**Comment by ctrueden** [comment]
Thanks for this. I have cherry-picked the "big cleanup" commit (56e72df) onto master. This avoids the needless commit-then-revert series before it (0c2ee8e and ac5e466). There was also a problem on my OS X system with the "line endings" commits, so I redid that one as f261be803463315ad6249b96ed904a4c5fc74392.

**Comment by dugilos** [comment]
Hello, I updated my local git reposity to get the plugin in its last version and I installed it (maven install) on my computer, Windows 7 64, and I have since some projects that doesn't compile anymore.

During compilations the library type of my projects is fixed to shared with no account of what I specified in the POM, I ran in debug mode to see what appends, and here is the result:
library-type
In the Library class instance, the attribute "type" seems to be correctly setted by the POM, the expression "this.type" seen by the debugger returns "executable", but the return of the method getType() is "shared" and this is the library type which is used during all the plugin execution.

The modification that brought this behavior is the "final" property of the "type" attribute.
before: <pre>    @Parameter
    private String type = SHARED;</pre>
now: <pre>  @Parameter
  private final String subSystem = "console";</pre>

By removing the property "final" my library type is back to normal during the plugin execution.
So I think that none of the @Parameter attributes should be final.

**Comment by ctrueden** [comment]
Thanks @dugilos!

**Comment by pauldaustin** [comment]
I'll look at this tomorrow. I'll remove the final flag from fields in the config and do a search in the code and manually remove the final keyword on parameters

Paul Austin
Revolution Systems Inc.

**Comment by ctrueden** [comment]
@pauldaustin In case you didn't already notice: @dugilos already fixed it in PR #172. So no worries!

**Pull request closed without merging**
