### PR TITLE
Add support for versioned shareable objects for amd64.Linux.gpp

### PR DESCRIPTION
**Pull request by markBowman**
As already supported by most other AOLs. For example libMyLibrary.so.2
Add compile scope to narUnpack mojo to correctly resolve dependencies.

### CODE REVIEW

**Comment by ctrueden** [comment]
@markBowman Thank you very much! (And in case you were curious: the buildhive errors are an unrelated issue.)

**Comment by markBowman** [comment]
Brilliant! Thanks. If it's not too cheeky, do you have any idea when you might push a new tag to maven central?

**Comment by ctrueden** [comment]
@markBowman Since you asked, I tried to cut a `3.2.1` release just now.

Unfortunately, it failed. It seems [I don't have permission to deploy `com.github.maven-nar` artifacts to OSS Sonatype](http://jenkins.imagej.net/job/Release-Version/463/console). I [asked a Sonatype Nexus admin to add me](https://issues.sonatype.org/browse/OSSRH-7237) but in the mean time, perhaps @dscho could do the honors. Otherwise, I will cut the release once I have such permission.

**Comment by markBowman** [comment]
Thank you. I really appreciate the excellent support.

**Comment by ctrueden** [comment]
All sorted now, and [nar-maven-plugin 3.2.2](https://oss.sonatype.org/content/repositories/releases/com/github/maven-nar/nar-maven-plugin/3.2.2/) is released! Should appear on Central within a few minutes.

**Pull request merged**
