### PR TITLE
Remove the property final on the @Parameter attributes.

### PR DESCRIPTION
**Pull request by dugilos**
In a pom I defined a library type as static, and during the execution of
the plugin the library type was set to shared which is the default
value.
By removing the keyword "final" on the attribute "type" in the class
Library, the build was back to normal.
The attribute "type" has the annotation @Parameter and thus its value 
is normally set from the pom by maven, but the property final seemed to 
prevent that.

So I removed the keyword "final" on all the @Parameter attributes.

### CODE REVIEW

**Comment by dugilos** [comment]
Hello, after leaving a comment in the pull request #168, I tested the modification on my side and all the IT tests are back to success, so here is a pull request for this correction :)

**Comment by ctrueden** [comment]
Thank you, makes total sense!

We may also want to change the Eclipse code style template to not insert final on private fields. We have this same problem in the ImageJ project, but it can be pretty easily sidestepped by avoiding the scenario where inserting final would make sense. E.g., if your private field does not assign a default value at declaration, and doesn't have exactly one assignment along each constructor code path, then it can't be marked final anyway.

**Comment by ctrueden** [comment]
And yeah: if you mark a field final, it wreaks havoc with reflection. Even though there is a hack to remove the final keyword at runtime, after which you can assign the value (kinda sorta), it does not work as expected in many scenarios. So definitely best to avoid marking any `@Parameter` fields as final.

**Comment by ctrueden** [comment]
I changed the style template: c0ad7e25f858ddcfd80c72705b379cae99022f19

**Pull request merged**
