### PR TITLE
Fixing windowsSdkHome and windowsSdkVersion functionality

### PR DESCRIPTION
**Pull request by kristofmoens**
Try to fix the issue with the forced use of a certain Windows SDK.

### CODE REVIEW

**Comment by ctrueden** [comment]
Thanks for your time and efforts.

Unfortunately, you have some autoformatting (?) stuff going on that again introduces many whitespace changes into the Msvc file. You also undid some of the recent README.md changes. Can you please reduce the patch to the minimum changes necessary to accomplish the goal? If you are new to editing git history, see [this guide](https://github.com/maven-nar/nar-maven-plugin/wiki/How-to-contribute#incorporating-fixes-into-the-pull-request-ie-rewriting-the-topic-branch).

**Comment by kristofmoens** [comment]
I'm sorry about those whitespaces and the README. I had some problems with Git when merging the branches and had to revert. I will create a new commit tonight. :-)

Would you be interested in a patch to use MSBuild for MSVC or would this not really be useful? Maybe I should create a different class for this?

**Comment by ctrueden** [comment]
> Would you be interested in a patch to use MSBuild for MSVC or would this not really be useful?

I am the wrong person to ask. It wouldn't be useful to _me_. But this is OSS. If it is useful to _you_, then do it—scratch your itch! As long as it does not break existing functionality, then no worries.

> Maybe I should create a different class for this?

You decide. Whatever it takes to make the code most [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), easy to understand and maintain.

**Comment by kristofmoens** [comment]
Is this last commit any better?

That itch will have to wait a bit. ;-)

**Comment by ctrueden** [comment]
@kristofmoens Thanks. That is pretty small, so I'll clean it up manually and merge to #201 in a bit.

**Comment by kristofmoens** [comment]
True, I should have left the '{', thanks for the clean-up!

**Comment by ctrueden** [comment]
OK, I rolled this patch into the main commit of #201.

**Pull request closed without merging**
