### PR TITLE
Msvc init

### PR DESCRIPTION
**Pull request by pauldaustin**
Added the Msvc CCTask configuration to the NarTestCompileMojo and NarVcprojMojo. This should allow the tests to find the compiler using the path and complete.

### CODE REVIEW

**Comment by ctrueden** [comment]
Rock on, we'll see how the Windows build gets on.

**Comment by ctrueden** [comment]
No dice: http://jenkins.imagej.net/job/NAR-Maven-Plugin-windows/62/console

**Comment by pauldaustin** [comment]
Is it possible to re-configure the jenkins windows build so that it has the invoker.debug=true set. That way we can verify which version of the compiler is being picked up and what the PATH settings look like?

If you try a build of a different branch does it work?

Is there anyone who can verify if the temp directory is out of space?

**Comment by ctrueden** [comment]
@pauldaustin Thanks for the reminder about the temp folder. I changed the build configuration, adding a call to delete all `%TMP%\_CL_*.ss` files before each build. But it seems that wasn't the problem:
```
+ cmd /c 'del /q "%TMP%\_CL_*.ss"'
Could Not Find C:\Users\VIRTUA~1\AppData\Local\Temp\_CL_*.ss
```
I also added `-Dinvoker.debug=true` to the `mvn` calll, but it doesn't immediately appear to have made any difference.

http://jenkins.imagej.net/job/NAR-Maven-Plugin-windows/68/console

I cannot remote to the Windows VM right now because I'm currently traveling. But can dig further next week when I am back, if you are stuck.

**Comment by pauldaustin** [comment]
The extra debug information gets put in the build.log for the test script.

For example.

http://jenkins.imagej.net/job/NAR-Maven-Plugin-windows/ws/target/it/it0003-jni/build.log


From there I was able to get the following PATH and the command run to compile. Is it possible to try that on the command line? Maybe try it with and without the PATH to see if there is a different between the default environment and the one constructed in the plugin

````
set PATH=C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\Tools;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Bin
cl  /c /nologo /EHsc /DNDEBUG /MD /GR /DWindows /DWIN32 "/Itarget\it\it0003-jni\target\nar\javah-include" "/IC:\msysgit\src\fiji\java\win32\jdk1.6.0_24\include" "/IC:\msysgit\src\fiji\java\win32\jdk1.6.0_24\include\win32" "/IC:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include" "/IC:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Include" C:\msysgit\workspace\target\it\it0003-jni\src\main\c\HelloWorldJNI.c
````

**Comment by ctrueden** [comment]
@pauldaustin Sorry for the long delay in reply. It's been a busy summer.

Looking at the most recent build log, the failure seems very likely related to this part:
```
[DEBUG] cmd /c "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64\cl"  /c /nologo /EHsc /DNDEBUG /MD /GR /DWIN32 /IC:\msysgit\workspace\NAR-Maven-Plugin-windows\target\it\it0003-jni\target\nar\obj\amd64-Windows-msvc /IC:\msysgit\workspace\NAR-Maven-Plugin-windows\target\it\it0003-jni\target\nar\obj\amd64-Windows-msvc /IC:\msysgit\workspace\NAR-Maven-Plugin-windows\target\it\it0003-jni\target\nar\javah-include /Ic:\msysgit\src\fiji\java\win64\jdk1.7.0_79\include /Ic:\msysgit\src\fiji\java\win64\jdk1.7.0_79\include\win32 "/IC:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include" "/IC:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Include" /FoHelloWorldJNI.-1771989671.obj C:\msysgit\workspace\NAR-Maven-Plugin-windows\target\it\it0003-jni\src\main\c\HelloWorldJNI.c
[DEBUG] Setting environment variable: PATH=C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcpackages;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\Tools;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Bin\x64;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\wbem
[DEBUG] Setting environment variable: SystemRoot=C:\Windows
[DEBUG] Setting environment variable: TMP=C:\Temp
[DEBUG] Execute:Java13CommandLauncher: Executing 'cmd' with arguments:
'/c'
'C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64\cl'
''
'/c'
'/nologo'
'/EHsc'
'/DNDEBUG'
'/MD'
'/GR'
'/DWIN32'
'/IC:\msysgit\workspace\NAR-Maven-Plugin-windows\target\it\it0003-jni\target\nar\obj\amd64-Windows-msvc'
'/IC:\msysgit\workspace\NAR-Maven-Plugin-windows\target\it\it0003-jni\target\nar\obj\amd64-Windows-msvc'
'/IC:\msysgit\workspace\NAR-Maven-Plugin-windows\target\it\it0003-jni\target\nar\javah-include'
'/Ic:\msysgit\src\fiji\java\win64\jdk1.7.0_79\include'
'/Ic:\msysgit\src\fiji\java\win64\jdk1.7.0_79\include\win32'
'/IC:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include'
'/IC:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Include'
'/FoHelloWorldJNI.-1771989671.obj'
'C:\msysgit\workspace\NAR-Maven-Plugin-windows\target\it\it0003-jni\src\main\c\HelloWorldJNI.c'

The ' characters around the executable and arguments are
not part of the command.
[ERROR] 'C:\Program' is not recognized as an internal or external command,
[ERROR] operable program or batch file.
```

In other words: the double quotes are being stripped from the command being passed to `cmd /c`.

@pauldaustin Ideas on how to fix? I thought I'd ask you first, in case you know where/how this might be happening. Otherwise we can dig into the code. But I didn't immediately find it after 10 minutes of grepping.

**Comment by ctrueden** [comment]
Also @GregDomjan, as another Windows guy—any chance the fix here is obvious to you?

**Comment by pauldaustin** [comment]
Curtis,

Which branch is this on?

I’m going off the grid for a few days but might be able to look next week.

I’ll run it through a debugger to see where the quotes get stripped off. Hopefully not in the ant code.

Paul

**Comment by ctrueden** [comment]
@pauldaustin It's the master branch.

**Comment by pauldaustin** [comment]
Thanks,

will look at this next week

**Comment by ctrueden** [comment]
@pauldaustin Any word?

There has been a burst of activity lately regarding MSVC, and NAR on Windows in general—so it would be really helpful to have a working Windows-based CI system for NAR.

Unfortunately, I am woefully unequipped to discuss or troubleshoot Windows-centric issues with NAR. But the good news is that @GregDomjan and @markjohndoyle are much more knowledgeable, and are paying attention (at least for the moment :wink:).

**Comment by pauldaustin** [comment]
Chris,

I’m going away for the next 3 weeks.

Also the code to launch the command has changed since what I had working due to some security issues with what I’d done. As such I have no idea now what the correct way to call the commands such that the environment gets passed through correctly.

It also gets confusing as the code delegates off to an ant task to launch the executable so trying to figure out what it’s doing was a little tricky and not something we could modify easily.

I’m also not a windows developer so don’t know all the ins and outs of calling command line tools.

Paul

**Comment by kristofmoens** [comment]
When I first used the nar-plugin I had a similar problem. 

But when I build now it seems to be working on my machine... Could you maybe rebuild again?
Build log:
>[INFO]
>[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ nar-maven-plugin ---
>[INFO] Building jar: c:\thalerng\synergy\nar-maven-plugin\target\nar-maven-plugin-3.3.0.jar
>[INFO]
>[INFO] --- maven-plugin-plugin:3.2:addPluginArtifactMetadata (default-addPluginArtifactMetadata) @ nar-maven-plugin ---
>[INFO]
>[INFO] --- maven-invoker-plugin:1.8:install (integration-test) @ nar-maven-plugin ---
>[INFO] Installing c:\thalerng\synergy\nar-maven-plugin\pom.xml to c:\thalerng\synergy\nar-maven-plugin\target\it-repo\com\github\maven-nar\nar-maven-plugin\3.3.0\nar-maven-plugin-3.3.0.pom
>[INFO] Installing c:\thalerng\synergy\nar-maven-plugin\target\nar-maven-plugin-3.3.0.jar to c:\thalerng\synergy\nar-maven-plugin\target\it-repo\com\github\maven-nar\nar-maven-plugin\3.3.0\nar-maven-plugin-3.3.0.jar
>[INFO]
>[INFO] --- maven-invoker-plugin:1.8:run (integration-test) @ nar-maven-plugin ---
>[INFO] Building: it-parent\pom.xml
>[INFO] ..SUCCESS (2.8 s)
>[INFO] Building: it0003-jni\pom.xml
>[INFO] ..SUCCESS (14.5 s)
>[INFO] Building: it0007-lib-shared\pom.xml
>[INFO] ..SUCCESS (12.9 s)
> ...
>[INFO] ..SUCCESS (8.9 s)
>[INFO] Building: it0027-dep-jni-native-lib-loader\pom.xml
>[INFO] ..SUCCESS (7.6 s)
>[INFO] Building: it0028-scope\pom.xml
>[INFO] ..SUCCESS (30.5 s)
>[INFO] -------------------------------------------------
>[INFO] Build Summary:
>[INFO]   Passed: 24, Failed: 0, Errors: 0, Skipped: 0
>[INFO] -------------------------------------------------
>[INFO]
>[INFO] --- maven-invoker-plugin:1.8:integration-test (integration-test) @ nar-maven-plugin ---
>[INFO] Building: it-parent\pom.xml
>[INFO] ..SUCCESS (3.0 s)
>[INFO] Building: it0003-jni\pom.xml
>[INFO] ..SUCCESS (15.1 s)
>...
>[INFO] Building: it0027-dep-jni-native-lib-loader\pom.xml
>[INFO] ..SUCCESS (8.7 s)
>[INFO] Building: it0028-scope\pom.xml
>[INFO] ..SUCCESS (29.5 s)
>[INFO]
>[INFO] --- maven-invoker-plugin:1.8:verify (integration-test) @ nar-maven-plugin ---
>[INFO] -------------------------------------------------
>[INFO] Build Summary:
>[INFO]   Passed: 24, Failed: 0, Errors: 0, Skipped: 0
>[INFO] -------------------------------------------------
>[INFO]
>[INFO] --- maven-install-plugin:2.5.1:install (default-install) @ nar-maven-plugin ---
>[INFO] Installing c:\thalerng\synergy\nar-maven-plugin\target\nar-maven-plugin-3.3.0.jar to C:\Users\kmoens\.m2\repository\com\github\maven-nar\nar-maven-plugin\3.3.0\nar-maven-plugin-3.3.0.jar
>[INFO] Installing c:\thalerng\synergy\nar-maven-plugin\pom.xml to C:\Users\kmoens\.m2\repository\com\github\maven-nar\nar-maven-plugin\3.3.0\nar-maven-plugin-3.3.0.pom
>[INFO] ------------------------------------------------------------------------
>[INFO] BUILD SUCCESS
>[INFO] ------------------------------------------------------------------------

**Comment by ctrueden** [comment]
@kristofmoens wrote:
> I think when I first used the nar-plugin, I had a similar problem on my first build. Can't remember if I had to change something.
>
> But when I build now, it seems to be working on my machine... Could you maybe rebuild again?

It would be helpful to know what you changed to address the issue. I ran the build again on our Windows Jenkins node and it [still fails](http://jenkins.imagej.net/job/NAR-Maven-Plugin-windows/90/console).

**Comment by markjohndoyle** [comment]
Hey all,

I'm actually one of those weird people that develop non-specific code on Windows. My target is normally linux so it also helps keeping things portablel. I use gcc and clang not msvc, in fact I don't have much experience using MSVC at all.

I'm a bit overloaded at the minute but I can probably test whether the nar plugin doesn't break when using other compilers on Windows.

**Pull request closed without merging**
