### PR TITLE
Msvc configuration

### PR DESCRIPTION
**Pull request by pauldaustin**
Added the new Msvc configuration class.

````
<msvc>
  <version>10.0</version>
  <windowsSdkVersion>7.1A</windowsSdkVersion>
</msvc>
````

The configuration allows defining the MS Visual Studio version number.
This will then auto detect the Visual Studio Home. If the version is not
specified it will look for the VSxxxCOMNTOOLS environment variables to
see which
versions exist and use the maximum available version.

The configuration also allows selecting the windowsSdkVersion. If not
specified it will look in the C:\Program Files (x86)\Microsoft
SDKs\Windows or C:\Program Files (x86)\Windows Kits for available
versions.

The linker and compilers will then be configured with default includes
and library paths from both the visual studio and windows sdk homes.

### CODE REVIEW

**Comment by ctrueden** [comment]
This looks like a great addition, but I'm a bit confused by the patch series. You have a commit, then a reversion, then another commit with a strange (truncated?) commit message. Then another commit with no message except "windows" as the subject.

Could you please rewrite these commits to be a little more clear about what they are attempting to accomplish? You can find a guide for doing that here: https://github.com/maven-nar/nar-maven-plugin/wiki/How-to-contribute#incorporating-fixes-into-the-pull-request-ie-rewriting-the-topic-branch

**Comment by pauldaustin** [comment]
Curtis,

Things got a little messed up with the commits as I had originally committed them to master and then created the branch. After that I changed development servers which caused a few commits.

I think the best thing to do will be for me to create a new branch from master with #168 and then apply my final changes from this pull request on top of of that. Then I can create a new pull request from that with proper comments.

**Comment by ctrueden** [comment]
@pauldaustin FWIW, you do not need to close and then open a new PR; you can instead force push changes to your branch, and the existing PR will be updated accordingly.

Thanks for your continued efforts on this!

**Comment by pauldaustin** [comment]
I had to delete the old branch from my repository as it got a little messed up while I was trying to do the merge.

Part of the issue was there were other commits that didn’t use the new code cleanup and formatting applied to them to the same files I’d modified. This made it really fragmented in terms of the diffs when I was trying to do the commits.

Paul

**Comment by ctrueden** [comment]
> I had to delete the old branch from my repository as it got a little messed up while I was trying to do the merge.

If you have a branch `badbranch` which is messed up, and a branch `goodbranch` which is exactly how you want, then you can do:
```
$ git checkout badbranch
$ git reset --hard goodbranch
$ git push --force origin badbranch
```
and your PR will automatically update with the state from `goodbranch`. Undesirable state from `badbranch` will no longer be present.

**Comment by ctrueden** [comment]
In short, you can think of a branch as a "pointer" to a particular commit in the tree. And `git reset --hard` is how you say "just update my pointer to point to X".

**Comment by ctrueden** [comment]
Anyway, I assume #170 is the continuation of this work now...

**Comment by pauldaustin** [comment]
Yes #170 is everything from #166 with the merge as the result of the code cleanup and formatting pull request. That was a real pain as other commits which didn’t have the code cleanup got applied on top so the merge required a lot of manual aligning of code to ensure that I didn’t miss other things.

**Pull request closed without merging**
