### PR TITLE
Linker default dependency Lib Order #236

### PR DESCRIPTION
**Pull request by manu4linux**
To use this new default dependency lib order please add 
`<narDefaultDependencyLibOrder>true</narDefaultDependencyLibOrder>`
under NAR config 
`<linker>`

### CODE REVIEW

**Comment by manu4linux** [comment]
This is to resolve #236 and https://groups.google.com/forum/#!topic/maven-nar/-scI_A58H5U

Default behavior of Nar is to work exactly as before if "narDefaultDependencyLibOrder" linker tag is not used.

**Comment by manu4linux** [comment]
@ctrueden Please comment when get chance to..

**Comment by manu4linux** [comment]
As always I have tested it on CentOs7.2 i386 vm and All NAR IT tests seem to pass except one "it0002-executable-static". This test fails for original code too due to non resolution of static -lstdc++ & others..

> [INFO] -------------------------------------------------
> [INFO] Build Summary:
> [INFO]   Passed: 25, Failed: 1, Errors: 0, Skipped: 0
> [INFO] -------------------------------------------------
> [ERROR] The following builds failed:
> [ERROR] *  it0002-executable-static/pom.xml
> [INFO] -------------------------------------------------
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 3:39.656s
> [INFO] Finished at: Fri Jun 10 13:46:44 PDT 2016
> [INFO] Final Memory: 24M/58M
> [INFO] ------------------------------------------------------------------------
>

**Comment by manu4linux** [comment]
@ctrueden thanks for the earlier feedback ! 
I have made the relevent changes as suggested, please have a look.

**Comment by manu4linux** [comment]
As before I have tested it on CentOs7.2 i386 vm and All NAR IT tests seem to pass except one "it0002-executable-static". This test fails for original code too due to non resolution of static -lstdc++ & others..

> 
> [INFO] -------------------------------------------------
> [INFO] Build Summary:
> [INFO]   Passed: 25, Failed: 1, Errors: 0, Skipped: 0
> [INFO] -------------------------------------------------
> [ERROR] The following builds failed:
> [ERROR] *  it0002-executable-static/pom.xml
> [INFO] -------------------------------------------------
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 3:46.645s
> [INFO] Finished at: Mon Jun 13 12:05:26 PDT 2016
> [INFO] Final Memory: 24M/59M
> [INFO] ------------------------------------------------------------------------

**Comment by ctrueden** [comment]
Awesome, thank you!

**Pull request merged**
