### PR TITLE
[WIP] appveyor tryfix

### PR DESCRIPTION
**Pull request by pavlus**
(In hope to fix appveyor builds)

### CODE REVIEW

**Comment by ctrueden** [comment]
@pavlus @GregDomjan I noticed that Travis CI now supports Windows. So maybe we can ditch AppVeyor and just add the Windows configuration to the Travis matrix. Worth a try!

**Comment by pavlus** [comment]
@ctrueden we can try, but there is still an issue with few (9 or 7 AFAIR) tests that require g++ and I'm not sure how to deal with it.

**Comment by GregDomjan** [comment]
Using 1 build system might be good, not sure if it will actually fix the outstanding though.

Quick review of logs from last failed, 3 main things to address

**File system issues?**
`it0031-push-deps-to-lowest-order-A,  it0032-directDepsOnly-success, it0037-directDepsOnlyTestScope-success`  failed due to dependency on 
`it0031-push-deps-to-lowest-order-agg` which failed due to inability to write output - cannot see cause at this point (Windows file lock? Virus checker? Out of space??)
` OUTPUT>LINK : fatal error LNK1104: cannot open file 'it0031-push-deps-to-lowest-order-B-1.0-SNAPSHOT.lib'`

**Appveyor doesn't seem to be configured to achieve 'simulate a multi-platform multi-aol deploy' **
`it0035-downstream-multi-aol` failed due to dependency on 
`it0034-secondary-execution-options` failed due to dependency on
`it0034-upstream-aol1-multi-aol + it0034-upstream-aol2-multi-aol`  due to mismatch with target platform and tools `amd64-Linux-gpp, amd64-Windows-gpp`

**Test name length limitation - Windows**
`it0033-directDepsOnly-link-transitive-deps` failed due to toolset path length limit being exceeded
This path is 260 chars, limit is 250 (or maybe 255)
`C:\projects\nar-maven-plugin\target\it\it0033-directDepsOnly-link-transitive-deps\it0033-directDepsOnly-link-transitive-deps-trans\target\nar\it0033-directDepsOnly-link-transitive-deps-trans-1.0-SNAPSHOT-amd64-Windows-msvc-shared\lib\amd64-Windows-msvc\shared`

**Comment by bchiodo** [comment]
I am closing since appveyor has been fixed since b77a04efc014107e9128324c116f1abda36ce6a7.

**Pull request closed without merging**
