### PR TITLE
Add support in Solaris/g++ configuration

### PR DESCRIPTION
**Pull request by eyalg1972**
Add support in compiling using gcc/g++ on Solaris sparc 64 bits

### CODE REVIEW

**Comment by ctrueden** [comment]
This is great, thanks! 😄 

However, it would be best to [squash these two commits together](https://github.com/maven-nar/nar-maven-plugin/wiki/How-to-contribute#incorporating-fixes-into-the-pull-request-ie-rewriting-the-topic-branch). I also want to give you a heads up that your commits are not associated with your GitHub account due to email address mismatch; you can see this by clicking one of your commits, then mousing over the little question mark glyph next to your name in the commit header.

If you could please squash and then force push, I will merge it!

**Comment by eyalg1972** [comment]
Hi,

I merge the commits to one and pushed, any changes I need to do in the pull request?

Thanks
Eyal

**Comment by ctrueden** [comment]
@eyalg1972 Thanks for your efforts. However, the commits are not squashed. You need to use `git rebase -i`. Please follow the link I posted above for details on how to do it.

**Comment by eyalg1972** [comment]
What do you mean? I used the commands- 
git rebase --interactive HEAD~2

And the result is one commit- 
Support compilation on Solaris 64 bits with g++ commit d1f8ca29a96affa5665c3896f72904edc65ff577

Which is the squashed result.

Eyal

**Comment by ctrueden** [comment]
If you look at the "Commits" tab above, you will see that you somehow ended up with a merge of your rebased commit with the older two-commit version. So there are four total commits here which would be merged. Perhaps you ran `git merge` after the rebase, instead of simply doing `git push --force` to update the remote to your rewritten version?

In any case, my goal is not to tie you up in bureaucracy, so I just cherry-picked d1f8ca29a96affa5665c3896f72904edc65ff577 directly.

**Comment by eyalg1972** [comment]
Thanks!!

Eyal

**Comment by eyalg1972** [comment]
Thanks Curtis.

What about the rest of the Pull requests?

Eyal

**Comment by ctrueden** [comment]
> What about the rest of the Pull requests?

Sorry for the delay. I reviewed them all. Some are merged now; I commented on how to move the others forward.

**Comment by eyalg1972** [comment]
No problems,  I am on vacation this week. but next week I will check the
comments.


Eyal

בתאריך 11 באפר׳ 2017 19:33,‏ "Curtis Rueden" <notifications@github.com> כתב:

**Pull request closed without merging**
