### PR TITLE
Improve implementation of executing command

### PR DESCRIPTION
**Pull request by eyalg1972**
Instead of using the "Execute" class of ANT, I am now using the standard Java execution process using ProcessBuilder.  Also- the executed command is printed so it is easy to see what might fail

### CODE REVIEW

**Comment by ctrueden** [comment]
In principle I am all for simplifying the command execution. However, this is a deep change which needs to be tested on several platforms. It makes me nervous to merge it without some community validation first.

Ideally we would have all the integration tests passing on all of the major platforms, so that we can verify that they all still work after this change. Unfortunately, this is not the current reality—some integration tests fail on some platforms, for reasons no one has had time to investigate.

May I ask why you felt this change is necessary? Does it fix specific problems you encountered? If so, would you be willing to write a new test which fails under the old execution method, but passes with this one?

**Comment by eyalg1972** [comment]
Hi,

I actually did here 2 things:

1) Replaced the ANT implementation- which I am not sure how it is
implemented with the newest implementation (Newest- from Java 1.5)
Since the NAR compilation is now done with Java 1.7, and Java 1.7 update 21
(If I am not mistaken) had modified the old way the Java used of
Runtime.exec, I prefered to be sure we have the recommendded way of
activating the commands (If the compilation was still with Java 1.5 or 1.6
it was less urgent).
2) Added to the log the command that is being executed, so in case of
failure we will have the full command already in the logs.

I can not remember now if there was a failure or not in any command with
the old implementation, but I did test the new implementaion on 4 platforms
and it works-

   - Windows 64 bits with MSVC
   - Linux 64 bits with g++
   - AIX 64 bits with g++
   - Solaris 64 bits with g++
   - AIX 64 bith with XLC_r will be tested in few weeks.

Regards

Eyal

**Comment by eyalg1972** [comment]
Regarding-

Ideally we would have all the integration tests passing on all of the major
platforms, so that we can verify that they all still work after this
change. Unfortunately, this is not the current reality—some integration
tests fail on some platforms, for reasons no one has had time to
investigate.

Can you tell me-

1) How do you run today the integration tests?
2) What tests fails and on which platforms?
3) Can I re-produce the failures?

I am not promising, but I can try to help here.

Eyal

**Comment by ctrueden** [comment]
> How do you run today the integration tests?

https://github.com/maven-nar/nar-maven-plugin/wiki/Testing

> 2) What tests fails and on which platforms?

On Windows, there is an issue: #223. A bit out of date now, though. Haven't tested lately.

On macOS, there have been issues in the past which were fixed (see #41), but now there are failures again, at least on my system. I filed new issue #267 documenting which ones.

> 3) Can I re-produce the failures?

I dunno! Try `mvn -Prun-its` and see what happens on your box! 😄 

> I am not promising, but I can try to help here.

I completely understand. No worries. Any progress you make is appreciated, but I have no expectations.

**Comment by eyalg1972** [comment]
Can I get example of the failures on both Platforms- Windows and MacOS?

I mean- the exact errors that you get on your environment?

Eyal

**Comment by eyalg1972** [comment]
I am running the Integration tests on my machine (WIndows 10, Java 1.7 and
3 different VS installed) and it pass.

Attaching log.

What am I not doing correct?

I will try to run it also on Mac in the next few days.

Eyal

**Comment by ctrueden** [comment]
> What am I not doing correct?

Probably, you are doing everything correctly. It's just that there is a lot of variation between environments. Our old Windows node which was failing ran Windows 7, likely with different version(s) of Visual Studio. It is a lot of work to test a wide variety of configurations.

**Comment by eyalg1972** [comment]
Can you attach me for the first failure-  The target folder?  so I can see
what is causing the error?

I already wrote you in the Mac OS issue that I found the source of the
problem-  Next week I will try to see if my proposed solution  is working.

Eyal

בתאריך 20 באפר׳ 2017 21:35,‏ "Curtis Rueden" <notifications@github.com> כתב:

**Comment by ctrueden** [comment]
I pushed all IT logs from that attempt to the same gist. [Here is `it0001-executable.log`](https://gist.github.com/ctrueden/551535b1e1fdba5bcd499ff0e2035afe#file-it0001-executable-log).

**Comment by eyalg1972** [comment]
Thanks Curtis,

However- this are the results on the Mac machine.
I already re-produce it and I believe that the problem is that the Mac now
does not pass the DYLD_LIBRARY_PATH to the surefire plugin process, so it
does not find the jnilib.
I suhhest to replace the NarSystem implementation- instead of calling
System.LoadLibrary with the module name (Which depends on
java.library.path), to use System.load which recieve full path.
I will test this locally on my machine next week.
[ Assuming it will work, I will try to do the change on seperate branch, do
we have somewhere in the code when we reference to the full path of the
artifact that was created?]

Regarding Windows failures-
1) Can you tell me- on that machine with Windows 7- Which VS are installed?
which Java version is used?
2) Can you send me the content of the target folder of the first failures?
I need only the build.log but the entire target folder to examine the
failure (FOr the MAC for example, I needed the surefile-reports folder)

Eyal

**Comment by ctrueden** [comment]
> Regarding Windows failures-
> 1) Can you tell me- on that machine with Windows 7- Which VS are installed?
> which Java version is used?

I'm sorry, I don't have that information anymore. The VM in question was probably infected with malware, so we shut it down permanently. And the person who set it up has left the project; I do not know its configuration specifically.

If your Windows environment has all passing tests, then that is great. I wouldn't worry too much about it. The main thing is that we need to get Appveyor builds working properly, which means creating a maven-nar organization Appveyor account.

**Comment by eyalg1972** [comment]
Can you clarify what do you mean by "The main thing is that we need to get
Appveyor builds working properly, which means creating a maven-nar
organization Appveyor account" ?
Who can create it and what is needed for it?
How do we run the tests on MacOS and Linux?

Also- Can you approve the pull request? (I hope in a week or two create a
fix for the MacOS problem)

Basically it is replacement of Runtime.exec with process builder, than
since Java 7 update 21 is recommennded (Actually- it is recommended since
Java 1.5, but in 1.7 update 21 they made some changes), I add few issues
with Runtime.exec in the past and always move to process builder
helped....  (In this case- it gives me also the option of printing to the
logs the command executed, which makes my life much easier, without the
need to run -X)

http://www.oracle.com/technetwork/java/javase/7u21-relnotes-1932873.html#jruntime
"Alternatively, the preferred way to create operating systems processes
since JDK 5.0 is using java.lang.ProcessBuilder. The ProcessBuilder class
has a much more complete API for setting the environment, working directory
and redirecting streams for the process."

It might resolve-  https://github.com/maven-nar/nar-maven-plugin/issues/225


Eyal

**Comment by eyalg1972** [comment]
Sorry- NOw I see that 225 is related to a different execution command.

A diffrent story (But even there- we can replace the makeExecutable
implementation with Java 1.7 implementation for setting the execute
permissions)

Eyal

**Comment by ctrueden** [comment]
> Can you clarify what do you mean by "The main thing is that we need to get Appveyor builds working properly, which means creating a maven-nar organization Appveyor account" ?

See #275.

**Comment by eyalg1972** [comment]
And what is required to create such account?

Since we are open source project? (I assume you want organizational
account)?

Eyal

**Comment by ctrueden** [comment]
A couple of updates on the CI: 1) I finally created the `maven-nar` AppVeyor account; see [the project page](https://ci.appveyor.com/project/maven-nar/nar-maven-plugin). The configuration needs work, though. 2) I activated the Travis CI build as well; see [here](https://travis-ci.org/maven-nar/nar-maven-plugin). So now it should be doable to configure these systems to test PRs more thoroughly cross-platform.

And a question: for executing processes, would it make sense to lean on [Apache Commons Exec](https://commons.apache.org/proper/commons-exec/)?

**Comment by eyalg1972** [comment]
The Apache Commons Exec still rely on Runtime.getRuntime().exec, If only it
was using the ProcessBuilder instead...

Eyal

**Comment by ctrueden** [comment]
Really sorry for my long silence on this PR, @eyalg1972.

I am going to merge it, and we'll see how it goes with Travis CI.

The AppVeyor CI still needs to be fixed, but that is definitely a separate issue from this change.

**Comment by eyalg1972** [comment]
Thanks!!

Eyal

**Pull request merged**
