### PR TITLE
Native lib loader searching also the "shared" directory and not only "jni"

### PR DESCRIPTION
**Pull request by thohai**
Hi!

I have a project setup with 3 projects where I use JNI to access a shared library using native lib loader.
However, the nativelibloader does not find the shared library as it only searches the JNI folder but not the shared folder thus resulting in an error that the library could not be loaded because the dependency was not found.

For me, this small change solves the problem.

Best
Thomas

### CODE REVIEW

**Comment by ctrueden** [comment]
Thanks @thohai. The first commit looks very good, but the second one mixes in tons of changes which I think you didn't intend as part of that patch. And actually, it appears to be a completely redundant patch with the current master.

Anyway, I merged a slightly cleaned up version of your patch to master. So hopefully this issue is resolved for you now.

**Comment by thohai** [comment]
Hi!

Thank you for cleaning up!
I intended only the one change in the NarSystemMojo anything else was 
not intended.

Best
Thomas

**Comment by thohai** [comment]
Hi! What jumped my mind: what about static depenencies in this context .. would there be a problem too?

**Comment by ctrueden** [comment]
@thohai I am far from an expert on native code. But I thought static linkage meant that dependencies are included in the resultant main binary? So they wouldn't be stored separately in the NAR, then?

**Comment by thohai** [comment]
@ctrueden ofc you are right ... complete blackout on my side .....

**Pull request closed without merging**
