### PR TITLE
Adding support for forcing direct dependencies

### PR DESCRIPTION
**Pull request by aciaccio**
The changes here fix issue 280:
Enhancement - The nar plugin should provide an option to restrict dependencies to direct dependencies only #280

Included is a set of automated tests that verify the new enhancement. Any and all feedback is welcome. Thanks folks!

### CODE REVIEW

**Comment by ctrueden** [comment]
I am traveling now but will try to find time to review this before end of June. In the meantime, if anyone else has time to do a review, that would be much appreciated!

**Comment by ctrueden** [comment]
@GregDomjan @sdedwards Since you spoke up on the issue #280: do you have any concerns or reservations about merging this? Ultimately I don't have a good intuition for whether adding this is a Bad Idea™. From my perspective, as long as backwards compatibility of existing build configuration and public API is maintained, and there are integration tests exercising it, merging seems OK to me, since it addresses @aciaccio's requirements.

**Comment by sdedwards** [comment]
@ctrueden I suppose giving the users more options to control dependencies isn't a Bad Idea. It definitely should not be the default behaviour though. Note that Maven will still try to resolve the whole dependency tree even with the `directDepsOnly` option set, i.e. the local repository must have all the libraries available even though we are only compiling/linking to the direct ones.

**Comment by ctrueden** [comment]
Thanks for the feedback, @sdedwards. I'll merge now so that @aciaccio can get this feature without further delays.

**Comment by aciaccio** [comment]
+1 to *not* being the default behavior. Yes Maven will still resolve the
dependency tree (although I believe using the fixes from
https://github.com/maven-nar/nar-maven-plugin/pull/270 are ultimately
required to assure us the link line is properly ordered). The changes
included with directDepsOnly happen at link line creation time, not
dependency resolution time. directDepsOnly simply enforces constraints when
creating the link line.

**Pull request merged**
